//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weiche.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weiche.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        internal static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Textures....
        /// </summary>
        internal static string choosetexture {
            get {
                return ResourceManager.GetString("choosetexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string createbutton {
            get {
                return ResourceManager.GetString("createbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        internal static string curve {
            get {
                return ResourceManager.GetString("curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation for diverging track (In meters).
        /// </summary>
        internal static string deviation {
            get {
                return ResourceManager.GetString("deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add embankment.
        /// </summary>
        internal static string embankment {
            get {
                return ResourceManager.GetString("embankment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Secondary Deviation!.
        /// </summary>
        internal static string invaliddeviation {
            get {
                return ResourceManager.GetString("invaliddeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Platform Fence Height!.
        /// </summary>
        internal static string invalidfenceheight {
            get {
                return ResourceManager.GetString("invalidfenceheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Length Multiplier!.
        /// </summary>
        internal static string invalidlength {
            get {
                return ResourceManager.GetString("invalidlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Additional Pier Height!.
        /// </summary>
        internal static string invalidpierheight {
            get {
                return ResourceManager.GetString("invalidpierheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Platform Height!.
        /// </summary>
        internal static string invalidplatformheight {
            get {
                return ResourceManager.GetString("invalidplatformheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Radius!.
        /// </summary>
        internal static string invalidradius {
            get {
                return ResourceManager.GetString("invalidradius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of Segments!.
        /// </summary>
        internal static string invalidsegements {
            get {
                return ResourceManager.GetString("invalidsegements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of Tracks!.
        /// </summary>
        internal static string invalidtracks {
            get {
                return ResourceManager.GetString("invalidtracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Platform Width (Far)!.
        /// </summary>
        internal static string invalidwidth_f {
            get {
                return ResourceManager.GetString("invalidwidth_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Platform Width (Near)!.
        /// </summary>
        internal static string invalidwidth_n {
            get {
                return ResourceManager.GetString("invalidwidth_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Z-Movement!.
        /// </summary>
        internal static string invalidzmovement {
            get {
                return ResourceManager.GetString("invalidzmovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert textures.
        /// </summary>
        internal static string invertexture {
            get {
                return ResourceManager.GetString("invertexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Length Multiplication (25,50,75,..) .
        /// </summary>
        internal static string lengthmultiplier {
            get {
                return ResourceManager.GetString("lengthmultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tracks.
        /// </summary>
        internal static string numberoftracks {
            get {
                return ResourceManager.GetString("numberoftracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Pier height (in m).
        /// </summary>
        internal static string pierheight {
            get {
                return ResourceManager.GetString("pierheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string platform {
            get {
                return ResourceManager.GetString("platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Fence.
        /// </summary>
        internal static string platformfence {
            get {
                return ResourceManager.GetString("platformfence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform height (in m).
        /// </summary>
        internal static string platformheight {
            get {
                return ResourceManager.GetString("platformheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Ramp.
        /// </summary>
        internal static string platformramp {
            get {
                return ResourceManager.GetString("platformramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Side.
        /// </summary>
        internal static string platformside {
            get {
                return ResourceManager.GetString("platformside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plarform Width (Far).
        /// </summary>
        internal static string platformwidth_f {
            get {
                return ResourceManager.GetString("platformwidth_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Width (Near).
        /// </summary>
        internal static string platformwidth_n {
            get {
                return ResourceManager.GetString("platformwidth_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PNG textures.
        /// </summary>
        internal static string pngtexture {
            get {
                return ResourceManager.GetString("pngtexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add point motor.
        /// </summary>
        internal static string pointmotor {
            get {
                return ResourceManager.GetString("pointmotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string pointswitch {
            get {
                return ResourceManager.GetString("pointswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve radius for player&apos;s track OR deviation (In meters).
        /// </summary>
        internal static string radius {
            get {
                return ResourceManager.GetString("radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string rail {
            get {
                return ResourceManager.GetString("rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture rails.
        /// </summary>
        internal static string railtexture {
            get {
                return ResourceManager.GetString("railtexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of segments.
        /// </summary>
        internal static string segments {
            get {
                return ResourceManager.GetString("segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        internal static string steel {
            get {
                return ResourceManager.GetString("steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        internal static string stone {
            get {
                return ResourceManager.GetString("stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        internal static string straight {
            get {
                return ResourceManager.GetString("straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tgplatform {
            get {
                object obj = ResourceManager.GetObject("tgplatform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tgswitch {
            get {
                object obj = ResourceManager.GetObject("tgswitch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tgtrack {
            get {
                object obj = ResourceManager.GetObject("tgtrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tgviaduct {
            get {
                object obj = ResourceManager.GetObject("tgviaduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tgviaduct1 {
            get {
                object obj = ResourceManager.GetObject("tgviaduct1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Gauge (in m).
        /// </summary>
        internal static string trackgauge {
            get {
                return ResourceManager.GetString("trackgauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viaduct.
        /// </summary>
        internal static string viaduct {
            get {
                return ResourceManager.GetString("viaduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viaduct Type.
        /// </summary>
        internal static string viaducttype {
            get {
                return ResourceManager.GetString("viaducttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z - adjustment.
        /// </summary>
        internal static string zadjust {
            get {
                return ResourceManager.GetString("zadjust", resourceCulture);
            }
        }
    }
}
