//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weiche.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weiche.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        internal static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Textures....
        /// </summary>
        internal static string choosetexture {
            get {
                return ResourceManager.GetString("choosetexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string createbutton {
            get {
                return ResourceManager.GetString("createbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        internal static string curve {
            get {
                return ResourceManager.GetString("curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation for diverging track (In meters).
        /// </summary>
        internal static string deviation {
            get {
                return ResourceManager.GetString("deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without embankment.
        /// </summary>
        internal static string embankment {
            get {
                return ResourceManager.GetString("embankment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert textures.
        /// </summary>
        internal static string invertexture {
            get {
                return ResourceManager.GetString("invertexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Length Multiplication (25,50,75,..) .
        /// </summary>
        internal static string lengthmultiplier {
            get {
                return ResourceManager.GetString("lengthmultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Fence.
        /// </summary>
        internal static string platformfence {
            get {
                return ResourceManager.GetString("platformfence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform height (in m).
        /// </summary>
        internal static string platformheight {
            get {
                return ResourceManager.GetString("platformheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Ramp.
        /// </summary>
        internal static string platformramp {
            get {
                return ResourceManager.GetString("platformramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Side.
        /// </summary>
        internal static string platformside {
            get {
                return ResourceManager.GetString("platformside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plarform Width (Far).
        /// </summary>
        internal static string platformwidth_f {
            get {
                return ResourceManager.GetString("platformwidth_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Width (Near).
        /// </summary>
        internal static string platformwidth_n {
            get {
                return ResourceManager.GetString("platformwidth_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PNG textures.
        /// </summary>
        internal static string pngtexture {
            get {
                return ResourceManager.GetString("pngtexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add point motor.
        /// </summary>
        internal static string pointmotor {
            get {
                return ResourceManager.GetString("pointmotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string pointswitch {
            get {
                return ResourceManager.GetString("pointswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve radius for player&apos;s track OR deviation (In meters).
        /// </summary>
        internal static string radius {
            get {
                return ResourceManager.GetString("radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not texture rails.
        /// </summary>
        internal static string railtexture {
            get {
                return ResourceManager.GetString("railtexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of segments.
        /// </summary>
        internal static string segments {
            get {
                return ResourceManager.GetString("segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        internal static string straight {
            get {
                return ResourceManager.GetString("straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z - adjustment.
        /// </summary>
        internal static string zadjust {
            get {
                return ResourceManager.GetString("zadjust", resourceCulture);
            }
        }
    }
}
